import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/dm-sans/latin-400.css";
import "@fontsource/dm-sans/latin-500.css";
import "@fontsource/dm-sans/latin-600.css";
import "@fontsource/lora/latin-400.css";
import "@fontsource/lora/latin-400-italic.css";
import "@fontsource/lora/latin-500.css";
import "@fontsource/italiana/latin-400.css";
import App from "./App.jsx";
import "./styles.css";
import "./pdf-text-layer.css";
import "./reader-markers.css";
import "./folders.css";
createRoot(document.getElementById("root")).render(<App />);
